### ISSUE TITLE
Obstacles generated on different trials appear on the same positions

### ISSUE THREAD

**Issue by bossdm** [resilient-swarms/argos-sferes#12]
Using 'distribute' in the configuration file does not appear to be placing obstacles differently depending on the trial. Currently obstacles are placed as follows:

`   <distribute>
      <position method="uniform" min="0,0,0" max="4,4,0" />
      <orientation method="constant" values="0,0,0" />
      <entity quantity="2" max_trials="200">
        <cylinder id="c" height="0.5" radius="0.1500" movable="false" />
      </entity>
    </distribute>`

**Comment by bossdm** [comment]
I guess it is supposed to work like that, since argos does not know about 'trials' ? and that is why you generated the robot positions inside our loop functions differently for each trial.

**Comment by daneshtarapore** [comment]
Yes. As the RNG seed is the same across the trials, the objects will be positioned similarly across trials.
