### ISSUE TITLE
Adding robots to swarm for base-line behaviours

### ISSUE THREAD

**Issue by daneshtarapore** [resilient-swarms/argos-sferes#13]
In baseline-behavs.argos, I notice that there are no robots in the arena. Even on adding 1 robot in the   <loop_functions library="lib/libbaseline-behavs-loopfunc.so"
                  label="baseline-behavs-loop-functions"
                  
                  trials="5"
                  robots="1"
                  fitfuntype="Aggregation"
		  output_folder="experiments">

has no effect. Also, a related noted,  the arena size has been scaled back considerably. Why is that?

**Comment by bossdm** [comment]
The robots are now placed correctly on trial per trial basis. 

However, it seems that the CThymioEntity is not recognising the 'rab' sensor:
```

terminate called after throwing an instance of 'argos::CARGoSException'
  what():  [FATAL] Failed to initialize the space.
[FATAL] Error while trying to distribute entities
[FATAL] Failed to initialize entity "thymio0".
[FATAL] Failed to initialize controllable entity "controller_0".
[FATAL] Can't set controller for controllable entity "controller_0"
[FATAL] While getting a component from a composable entity
[FATAL] Component "rab" does not exist in "thymio0"
```


In the configuration files (see README.md for which ones to use), I have commented out the range_and_bearing sensors and actuators for now. If you want to see what is happening you can uncomment these again.

On a side note, why put the batchsize and initial population as low as 20 ?

**Comment by daneshtarapore** [comment]
Without changing any of your code, I tried,

danesh@danesh-lafite:~/argos-sferes$ ./bin/baseline_behaviour
experiments/baseline-behavs.argos
[INFO] Not using threads
[INFO] Using random seed = 413068
[INFO] Using simulation clock tick = 0.1
[INFO] Total experiment length in clock ticks = 12000
[INFO] Loaded library "./lib/libbaseline-behavs.so"
[INFO] Loaded library "./lib/libbaseline-behavs-loopfunc.so"
Segmentation fault (core dumped)

**Comment by daneshtarapore** [comment]
Also, running argos3 -c experiments/baseline-behavs.argos
[INFO] Loaded library
"/usr/lib/argos3/libargos3plugin_simulator_pointmass3d.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_eyebot.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_spiri.so"
[INFO] Loaded library
"/usr/lib/argos3/libargos3plugin_simulator_entities.so"
[INFO] Loaded library
"/usr/lib/argos3/libargos3plugin_simulator_qtopengl.so"
[INFO] Loaded library
"/usr/lib/argos3/libargos3plugin_simulator_prototype.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_footbot.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3core_simulator.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_epuck.so"
[INFO] Loaded library "/usr/lib/argos3/libargos3plugin_simulator_media.so"
[INFO] Loaded library
"/usr/lib/argos3/libargos3plugin_simulator_dynamics3d.so"
[INFO] Loaded library
"/usr/lib/argos3/libargos3plugin_simulator_dynamics2d.so"
[INFO] Loaded library
"/usr/lib/argos3/libargos3plugin_simulator_genericrobot.so"
[INFO] Not using threads
[INFO] Using random seed = 889916
[INFO] Using simulation clock tick = 0.1
[INFO] Total experiment length in clock ticks = 12000
[INFO] Loaded library "./lib/libbaseline-behavs.so"
[FATAL] Error initializing loop functions
[FATAL] Can't load library "lib/libbaseline-behavs-loopfunc.so" even after
trying to add extensions for shared library (so) and module library (so):
/usr/lib/argos3/lib/libbaseline-behavs-loopfunc.so:
/usr/lib/argos3/lib/libbaseline-behavs-loopfunc.so: cannot open shared
object file: No such file or directory
/usr/lib/argos3/lib/libbaseline-behavs-loopfunc.so.so: /usr/lib/argos3/lib/
libbaseline-behavs-loopfunc.so.so: cannot open shared object file: No such
file or directory
/usr/lib/argos3/lib/libbaseline-behavs-loopfunc.so.so: OK

Upon further investigation, I see the files may not have been linked
properly: /home/danesh/argos-sferes/lib/libbaseline-behavs-loopfunc.so:
/home/danesh/argos-sferes/lib/libbaseline-behavs-loopfunc.so: undefined
symbol: _ZN17BaseLoopFunctions19get_embodied_entityEm

Can you add your base class loop functions to the cmakelist here;
add_library(base_loopfunctions SHARED
  src/core/base_loop_functions.h
  src/core/base_loop_functions.cpp
)

**Comment by bossdm** [comment]
Hi
You are right about that. If you use the Debug setting for that command, you should be able to see that it tries to do

`m_pcRABA->ClearData()`

but the m_pcRABA and m_pcRABS are null.


If you try the other command 
`./bin/behaviour_evolcvt400D experiments/multiagent_spirit.argos`
you should be able to run it for a while, as in that case I just continue with the proximity sensors only.

**Comment by bossdm** [comment]
If you comment in the config file the range_and_bearing actuator and sensor, then you should also be getting the same error message as I wrote above.

**Comment by bossdm** [comment]
> Upon further investigation, I see the files may not have been linked properly: /home/danesh/argos-sferes/lib/libbaseline-behavs-loopfunc.so: /home/danesh/argos-sferes/lib/libbaseline-behavs-loopfunc.so: undefined symbol: _ZN17BaseLoopFunctions19get_embodied_entityEm Can you add your base class loop functions to the cmakelist here; add_library(base_loopfunctions SHARED src/core/base_loop_functions.h src/core/base_loop_functions.cpp )

The lines 
`add_library(base_loopfunctions SHARED
  src/core/base_loop_functions.h
  src/core/base_loop_functions.cpp
)`

are already at line 219. The problem should be in one of the `target_link_libraries` I suppose.

**Comment by bossdm** [comment]
I have now added the base_loopfunctions to line 297 and it now links correctly when using 
`argos3 -c experiments/baseline-behavs.argos
`

**Comment by bossdm** [comment]
issue is now solved: the error was due to thymio installation (make sure you have latest thymio version and check installation prefix is the same as for argos-sferes)
