### ISSUE TITLE
Issue with parallel eval

### ISSUE THREAD

**Issue by bossdm** [resilient-swarms/argos-sferes#16]
In running the parallel code on github I can see some issues:

1. the multiagent_spirit causes segmentation fault:

> ^[[1;32m[INFO] Not using threads^[[0m
^[[1;32m[INFO] Using random seed = ^[[0m^[[1;32m1^[[0m
^[[1;32m[INFO] Using simulation clock tick = ^[[0m^[[1;32m0.2^[[0m
^[[1;32m[INFO] Total experiment length in clock ticks = ^[[0m^[[1;32m1000^[[0m
^[[1;32m[INFO] Loaded library "^[[0m^[[1;32m./lib/libnn_controller.so^[[0m^[[1;32m"^[[0m
^[[1;32m[INFO] Loaded library "^[[0m^[[1;32m./lib/libevolution_loopfunctionscvt576D.so^[[0m^[[1;32m"^[[0m
^[[1;32m[INFO] The physics engine "^[[0m^[[1;32mdyn2d_0^[[0m^[[1;32m" will perform ^[[0m^[[1;32m5^[[0m^[[1;32m iterations per tick (dt = ^[[0m^[[1;32m0.04^[[0m^[[1;32m sec)^[[0m
^[[1;32m[INFO] No visualization selected.^[[0m
Loaded 5000 centroids.
sferes2 version: (const char*)"f731bfb04a48a475dfedbfdb180d77054498557f"
seed: 1562676388
^[[0m^[[0m/tmp/slurmd/job10835/slurm_script: line 24: 241422 Segmentation fault      (core dumped) ${jobtocome}

2. the sdbc is running fine; however, it prints:

> [[0m^[[0m^[[0m^[[0m^

 repeatedly; I think this is the color setting for the argos printing. you can see this always in outputfiles in IRIDIS, for example, 

> ^[[1;32m[INFO] Not using threads^[[0m
> ^[[1;32m[INFO] Using random seed = ^[[0m^[[1;32m1^[[0m
> ^[[1;32m[INFO] Using simulation clock tick = ^[[0m^[[1;32m0.2^[[0m
> ^[[1;32m[INFO] Total experiment length in clock ticks = ^[[0m^[[1;32m1000^[[0m
> ^[[1;32m[INFO] Loaded library "^[[0m^[[1;32m./lib/libnn_controller.so^[[0m^[[1;32m"^[[0m
> ^[[1;32m[INFO] Loaded library "^[[0m^[[1;32m./lib/libevolution_loopfunctionscvt10D.so^[[0m^[[1;32m"^[[0m
> ^[[1;32m[INFO] The physics engine "^[[0m^[[1;32mdyn2d_0^[[0m^[[1;32m" will perform ^[[0m^[[1;32m5^[[0m^[[1;32m iterations per tick (dt = ^[[0m^[[1;32m0.04^[[0m^[[1;32m sec)^[[0m
> ^[[1;32m[INFO] No visualization selected.^[[0m

**Comment by daneshtarapore** [comment]
Hi David,

On Sat, Jul 6, 2019 at 6:27 PM bossdm <notifications@github.com> wrote:

> In running the parallel code on github I can see some issues:
>
>    1.
>
>    the multiagent_spirit causes segmentation fault
>
> How do you run it. Will need more info to replicate the error. Have you
tried to debug the issue?


>
>    1.
>    2.
>
>    the sdbc is running fine; however, it prints:
>
> [[0m^[[0m^[[0m^[[0m^
>
> repeatedly; I think this is the color setting for the argos printing. you
> can see this always in outputfiles in IRIDIS, for example,
>
> ^[[1;32m[INFO] Not using threads^[[0m
> ^[[1;32m[INFO] Using random seed = ^[[0m^[[1;32m1^[[0m
> ^[[1;32m[INFO] Using simulation clock tick = ^[[0m^[[1;32m0.2^[[0m
> ^[[1;32m[INFO] Total experiment length in clock ticks =
> ^[[0m^[[1;32m1000^[[0m
> ^[[1;32m[INFO] Loaded library
> "^[[0m^[[1;32m./lib/libnn_controller.so^[[0m^[[1;32m"^[[0m
> ^[[1;32m[INFO] Loaded library
> "^[[0m^[[1;32m./lib/libevolution_loopfunctionscvt10D.so^[[0m^[[1;32m"^[[0m
> ^[[1;32m[INFO] The physics engine "^[[0m^[[1;32mdyn2d_0^[[0m^[[1;32m" will
> perform ^[[0m^[[1;32m5^[[0m^[[1;32m iterations per tick (dt =
> ^[[0m^[[1;32m0.04^[[0m^[[1;32m sec)^[[0m
> ^[[1;32m[INFO] No visualization selected.^[[0m
>
>
I did not notice that while running it on my system. Perhaps you can try it
on your laptop to see if you have the same issue.

Best,
Danesh.

**Comment by bossdm** [comment]
Hi,

For the multiagent_spirit, you can use 

`./bin/behaviour_evolcvt576D  config`

where config is the configuration file I sent via email.


Normally the laptop does not give symbols like ^[[1;32m or  ^[[0m^[, I think because the color actually works on the terminal, whereas in the outputfile it would just print some additional symbols with no meaning. I am not sure how to make the output go to some outputfile instead on my laptop.

**Comment by bossdm** [comment]
I will see what happens on my laptop. The runs that started yesterday on iridis have finished, after 20 hours it seems that no generation is finished.

**Comment by bossdm** [comment]
the segmentation fault does not seem to happen on my laptop.

On IRIDIS,I notice that changing the setting 

> ntasks-per-node=1

makes the algorithm run faster. I still have to see whether that is faster than the version without parallelisation; it does not look too impressive at the moment.

**Comment by bossdm** [comment]
the reason why the laptop is working may be because the TBB is not being found:


> Could NOT find TBB (missing: tbbmalloc tbbmalloc_proxy) (found version "2017.0")
Unable to find TBB. Will not be able to run sferes eval::Parallel

In IRIDIS, as you might recall, I needed to manually specify the location of the TBB libraries.

**Comment by bossdm** [comment]
I notice in mpga.cpp they have a line:

>    /* The master sleeps to give enough time to the slaves to
    * initialize and suspend properly. If not enough time is given
    * here, the master will hang later on. */
   ::sleep(3);

Would we need something similar ?

**Comment by bossdm** [comment]
Interestingly, I notice that using the SDBC 10D descriptor on the login node IRIDIS in terminal, with random seed 0 and 5 trials in the config, that the code starts to hang after the first 5 trials:


> [INFO] Not using threads
[INFO] Using random seed = 86833
[INFO] Using simulation clock tick = 0.2
[INFO] Total experiment length in clock ticks = 600
[INFO] Loaded library "./lib/libnn_controller.so"
[INFO] Loaded library "./lib/libevolution_loopfunctionscvt10D.so"
[INFO] The physics engine "dyn2d_0" will perform 5 iterations per tick (dt = 0.04 sec)
[INFO] No visualization selected.
Loaded 5000 centroids.
sferes2 version: (const char*)"f731bfb04a48a475dfedbfdb180d77054498557f"
seed: 1562969073
[INFO] Using random seed = 210733
[INFO] Using random seed = 268531
[INFO] Using random seed = 452677
[INFO] Using random seed = 552876
[INFO] Using random seed = 651303

Maybe this confirms the above post ?

Also notice that the strange symbols related to the colors disappear when the random seed info is printed.

Update: the number of times the info is printed seems to be quite random, though always multiples of the number of trials.

**Comment by bossdm** [comment]
ok i have identified the problem. if i put sleep(1) at the end of the parent's if condition, the code progresses much further but eventually still hangs. so the parent should wait long enough for the child to finish.

see zombie processes https://www.bogotobogo.com/Linux/linux_process_and_signals.php

Update: one of the runs seemed to continue for a long time, but then, when it finished the first generationm=, it gave the following error:

> writing...archive_0
> _write_progress 
> terminate called after throwing an instance of 'boost::archive::archive_exception'
>   what():  output stream error
> submit_single_job.sh: line 10: 25788 Aborted                 (core dumped) ./bin/behaviour_evolcvt10D experiments/Gomes_walls_and_robots_std.argos

**Comment by daneshtarapore** [comment]
On Mon, Jul 8, 2019 at 7:13 PM bossdm <notifications@github.com> wrote:

> ok i have identified the problem. if i put sleep(1) at the end of the
> parent's if condition, the code progresses much further but eventually
> still hangs. so the parent should wait long enough for the child to finish.
>
No, the wait function should handle this. Read the system call information
for these functions. Have tried what you suggest and
a. It is not efficient.
b. The seconds all add up quickly to drastically increase computational
time.

**Comment by bossdm** [comment]
sleep was not proposed as a solution, merely to give some insight. putting wait(NULL) in the parent did not help. I tried that and also tried additionally putting ::raise(SIGCHLD) in the child before the exit), which also did not help.

**Comment by daneshtarapore** [comment]
WAIT(NULL) will just return once any process exits -- not necessarily the
child. So when I tried it I found that quite often the fitness &
descriptors would not be written in the shared memory.

Best,
Danesh.

**Comment by bossdm** [comment]
could we use waitpid somehow ?

> https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.2.0/com.ibm.zos.v2r2.bpxbd00/rtwaip.htm

I also see  in the mpga.cpp:

`tSlavePID = ::waitpid(-1, &nSlaveInfo, WUNTRACED);`

**Comment by daneshtarapore** [comment]
That is what we are using.

**Comment by bossdm** [comment]
I tried setting the first parameter to -1, that seems to keep the job running for longer, without using sleep.

However i would think it has the same problem as you mention with wait(NULL)

**Comment by daneshtarapore** [comment]
We may not want to do that as -1 keeps the parent waiting for any child
that exits. We need to wait specifically for the child running the
evaluation.

Best,
Danesh.

**Comment by bossdm** [comment]
Yes agreed.

Seems that without any changes to your code, when I submit the job with 8 cores without printing the random seed each time there seem to be two outcomes (50/50 probability approx.).

Either the algorithm works as before, simply outputting the strange symbol. 

In the other case, the algorithm works well, blasingly fast (150 generations in 8 minutes). The boost exception was due to the filesytem being full, can be avoided by not setting the seed 0. 

Why the difference is not clear, it appears to be quite random. At least we know it has something to do with the parent not waiting long enough on the child. unlike the mpga code we can't put the ::sleep code where we create the forks because that would be repeated over and over again. would it be difficult to create multiple loop functions like the mpga example ? None of the loop function values seem to depend on values from those obtained during other individuals' trials.

**Comment by daneshtarapore** [comment]
Can you change 

 size_t unShareMemSize = (BEHAV_DIM + 1) * sizeof(float);

to

 size_t unShareMemSize = (BEHAV_DIM + 1) * sizeof(Real);

It is on line 346 of evol_loop_functions.h

Do you still get the segmentation fault?

**Comment by bossdm** [comment]
nice find, that helped, I did not notice the difference. This seems to imply that the float vs Real difference is small enough such that it only starts to matter for large arrays.

**Comment by bossdm** [comment]
the color printing issue is now also resolved, I used LOG and LOGERR as used in LaunchARGoS in the mpga example (l. 201+)

Unfortunately, the problem with half of the runs not going beyond generation zero continues.

**Comment by daneshtarapore** [comment]
I think, depending on the architecture, Real is sometimes a typedef of
double and not of float.

**Comment by bossdm** [comment]
I was able to reduce the hanging rate, by adding more LOG.Flush and LOGERR.Flush across various places, and by including the destructor of the simulator in the child process. Now it hangs only once every 10-15 runs.

**Comment by daneshtarapore** [comment]
Can we replace

            int nSlaveInfo;
            pid_t tSlavePID = ::waitpid(pid,&nSlaveInfo, WUNTRACED);

with
            siginfo_t siginfo;
            ::waitid(P_PID, pid, &siginfo, WEXITED);

Reason being that waitpid with *WUNTRACED*

also return if a child has stopped (but not traced via *ptrace
<https://linux.die.net/man/2/ptrace>*(2)). Status for *traced* children
which have stopped is provided even if this option is not specified.(see
https://linux.die.net/man/2/waitid).

So if a child has been stopped but not terminated, waitpid will still
return it;


This still does not explain why the parent hangs, but it may be safer to
use  ::waitid(P_PID, pid, &siginfo, WEXITED); because*  WEXITED* -- Wait
for children that have terminated.

**Comment by daneshtarapore** [comment]
We can also check the returned value of waitid;

see https://linux.die.net/man/2/waitid

*waitid*(): returns 0 on success or if *WNOHANG* was specified and no
child(ren) specified by *id* has yet changed state; on error, -1 is
returned. Each of these calls sets *errno* to an appropriate value in the
case of an error.

**Comment by bossdm** [comment]
Hi,

I will try that one.

This reminds me of something I did in a previous version. 

I did this one or two versions ago 

```
        //end of child
            exit(2);
        }
        else if(pid > 0)
       {
            int nSlaveInfo;
	    do{
            pid_t tSlavePID = ::waitpid(pid,&nSlaveInfo, WUNTRACED);

	    }while(!WIFEXITED(nSlaveInfo));
```

This one should also wait for exit, at least so far as I understand, but did not seem to work.

**Comment by bossdm** [comment]
alright I think we have made it.  30-40 runs without hanging.

Your suggestion, with the addition of exit(2) instead of exit(1) in the child, did the trick. maybe let's keep the issue open for a while longer since the issue is stochastic.

**Comment by daneshtarapore** [comment]
what does exit(2) do? why does it work when exit(1) does not?

**Comment by bossdm** [comment]
I based that on the following :

> WIFEXITED(status)
    returns true if the child terminated normally, that is, by calling exit(3) or _exit(2), or by returning from main().

now that I read again, I might need to use an underscore.

**Comment by daneshtarapore** [comment]
On Thu, Jul 11, 2019 at 11:22 AM bossdm <notifications@github.com> wrote:

> I based that on the following :
>
> WIFEXITED(status)
> returns true if the child terminated normally, that is, by calling exit(3)
> or _exit(2), or by returning from main().
>
> now that I read again, I might need to use an underscore.
>
Okay, but we are using *WEXITED *--

Wait for children that have terminated.
We are not using WIFEXITED, right?

**Comment by bossdm** [comment]
Yes, we are using WEXITED.

I could be wrong in diagnosing a difference. There is the possibility that I was too quick to judge one of the runs based on the output; perhaps the run that did not show progress actually was ongoing and would show progress a bit later.

So based on that description 'Wait for children that have terminated. ', any exit could potentially work.

**Comment by daneshtarapore** [comment]
On Thu, Jul 11, 2019 at 11:41 AM bossdm <notifications@github.com> wrote:

> Yes, we are using WEXITED.
>
> I could be wrong in diagnosing a difference. There is the possibility that
> I was too quick to judge one of the runs based on the output; perhaps the
> run that did not show progress actually was ongoing and would show progress
> a bit later.
>
> So based on that description 'Wait for children that have terminated. ',
> any exit could potentially work.
>
Yes, that is what I think.

**Comment by bossdm** [comment]
I will merge with the parallel branch a bit later; I have made some changes to the master, I need to finish those first.

**Comment by bossdm** [comment]
using EXIT_SUCCESS instead of 2 appears to be horrible (two times it hangs even before starting to print ARGoS stuff, two other times it has the traditional hanging issue).

 maybe let's keep exit(2) rather than exit(1) since we have established with certainty that it works 50 out of 50 times; maybe my initial explanation does make sense.

**Comment by bossdm** [comment]
I have now noticed that in runs with longer wall time, the issue is still there in some of the runs. Also, when considering the larger behavioural descriptor none of them seem to finish generation 0.

As discussed I am going to remove quits on collision. Besides the mentioned reasons, it also helps to remove variability in time consumption to avoid the trivial explanation that it is just due to simulation time differences.

**Comment by daneshtarapore** [comment]
I have placed a number of print statements to understand what is going on.

Anyways, I am running a test run with the following:

#!/bin/bash

#SBATCH --ntasks-per-node=8     # Tasks per node
#SBATCH --nodes=1                # Number of nodes requested
#SBATCH --time=0:15:00          # walltime
#SBATCH --mem=20G
#SBATCH --job-name=dt_8cores


# mail alert at start, end and abortion of execution
#SBATCH --mail-type=ALL

# send mail to this address
#SBATCH --mail-user=tarapore.d.s@@gmail.com


./bin/behaviour_evolcvt10D exp_1.argos #> $SLURM_JOB_ID.out 2>
$SLURM_JOB_ID.err


The thing is when I login into the node running the job, I see only two
processes running -- one at 100% (assuming it's the child) and one at 0%
(assuming it's the waiting parent);
   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+
COMMAND
296499 dst1m17   20   0  209920  20280   7004 R 100.0  0.0   8:54.81
behaviour_evolc


296460 dst1m17   20   0    9528   1392   1160 S   0.0  0.0   0:00.00
slurm_script


296491 dst1m17   20   0  209920  27228   9120 S   0.0  0.0   0:01.38
behaviour_evolc


299929 dst1m17   20   0  188860   2628   1024 S   0.0  0.0   0:00.00 sshd



299930 dst1m17   20   0   22204   2116   1568 S   0.0  0.0   0:00.00 bash



300037 dst1m17   20   0   69040   2672   1568 R   0.0  0.0   0:00.07 top



No generations are logged within the wall-time. So am assuming there is no
parallelization and it's just one parent and child running; am trying to
understand why. Running cmake does find the tbb libs too; Any ideas?

Also, when you find the evolutionary process 'hanging' -- have you seen if
the load is similar to this?

**Comment by bossdm** [comment]
Hi,

I also had some trouble understanding the output of _top_ on iridis. However, I see a low amount of processes regardless of whether the job is succeeding or not.  (EDIT: ignore this, see post below)

I saw that when it is hanging, the print statements you added are similarly correct as the non-hanging case as far as I can see, just 10 times less statements.

**Comment by bossdm** [comment]
I just checked again: when it is succeeding it seems to be parallelising pretty good (5 or more close to 100%). From top of my head, when it is failing it has one close to 100% and one or more close to zero (don't remember how many)

**Comment by daneshtarapore** [comment]
So it seems when it is what you call as failing, it's just because it has
not been given cores to run on. Right?

Can you double check. If this is true, can you please raise an issue on the
iridis forum with details on specific job you have run so they can check
job accounting details?

Best,
Danesh.

**Comment by bossdm** [comment]
I will double check again to confirm.

> because it has not been given cores to run on 

that would be one option. would it be possible that for some reason no more forks are created at some point, so that even when iridis gives me many cores, there are no processes created to use them.

**Comment by daneshtarapore** [comment]
On Fri, Jul 12, 2019 at 12:55 AM bossdm <notifications@github.com> wrote:

> I will double check again to confirm.
>
> because it has not been given cores to run on
>
> that would be one option. would it be possible that for some reason no
> more forks are created at some point, so that even when iridis gives me
> many cores, there are no processes created to use them.
>

If you do a tail on the ARGOS output logs, you should be able to see if
child processes are still being forked out or not.

Best,
Danesh.

**Comment by bossdm** [comment]
there are different children at the end of the output log but isn't that what you would expect in both cases ?
for example, even if there is only one child at a time, the child's PID would always change right ?

**Comment by daneshtarapore** [comment]
On Fri, Jul 12, 2019 at 1:33 AM bossdm <notifications@github.com> wrote:

> there are different children at the end of the output log but isn't that
> what you would expect in both cases ?
> for example, even if there is only one child at a time, the child's PID
> would always change right ?
>
Yes, it would change. But are more lines being appended to the log output?

--Danesh

**Comment by bossdm** [comment]
it seems to hang completely, not adding any more lines.

**Comment by bossdm** [comment]
one avenue I had thought before was that it has to do with the printing in cvt_map_elites. based on the above that seems to be more likely, since it seems always after above 30 thousand lines of printing. I have tried flush() and close() of the output streams. the binary would be a possible cause but then not sure how you could change anything there.

**Comment by bossdm** [comment]
I seem to only notice the issue when there are many jobs going on at the same time; it could be coincidence, maybe not. 

Did you notice the issue before with a single job running at a time ?

**Comment by daneshtarapore** [comment]
Hi,

I noticed this issue with a single job running as well: i.e. two processes
-- one at 100% and one at 0%.

Best,
Danesh.

**Comment by daneshtarapore** [comment]
Another point, not sure if it's relevant:

Am using  tbb version 2017 on my system, but version 2018 on IRIDIS. Could
it be an issue/bug with the tbb version 2018?

**Comment by bossdm** [comment]
I don't see the MPGA example using TBB. Are you sure we need it ?

I have tried to run without TBB and it still seems reasonably fast (printed until generation 12 after 5 minutes) and over 15 instances did not hang.

**Comment by daneshtarapore** [comment]
On Fri, Jul 12, 2019 at 11:42 AM bossdm <notifications@github.com> wrote:

> I don't see the MPGA example using TBB. Are you sure we need it ?
>
Yes, sferes needs ttb to run eval::Parallel

Am printing out loads of stuff and keeping track of all 'living' forked
children in a vector. Across 3-4 runs, I observe that one to three children
get stuck somewhere.
a. either in making copies of nn
b. or after running just one trial of 50

For case a, the cpu load for the thee running children showed at 100%. So
they were definitely doing something.

--D

**Comment by bossdm** [comment]
perhaps we could copy the neural network before the fork ?

**Comment by daneshtarapore** [comment]
On Fri, Jul 12, 2019 at 12:18 PM bossdm <notifications@github.com> wrote:

> perhaps we could copy the neural network before the fork ?
>

That is just one of the place it hangs sometimes. And if we do that, we
defeat the whole purpose of the fork; to prevent simultaneous use of the
variables across processes

**Comment by bossdm** [comment]
sferes2 does mention:

> use of MPI to distribute the computational cost on clusters;

does that mean it is required or just something you can additionally do ?

**Comment by daneshtarapore** [comment]
On Fri, Jul 12, 2019 at 1:08 PM bossdm <notifications@github.com> wrote:

> sferes2 does mention:
>
> use of MPI to distribute the computational cost on clusters;
>
> does that mean it is required or just something you can additionally do ?
>
It is required if you need to distribute load across nodes on a network --
not just across the cores on a node.

**Comment by bossdm** [comment]
I have merged the parallel to the master. 

I have noticed that when turning random seed to 0, which prints some message all the time, the 5 minute experiments no longer hang.  Could it be that flushing without writing any text being left to flush is somehow causing problems. see the definition of Reset:

> void CSimulator::Reset() {
      /* Reset terminated flag */
      m_bTerminated = false;
      /* if random seed is 0 or is not specified, init with the current timeval */
      if(m_bWasRandomSeedSet) {
         CRandom::SetSeedOf("argos", m_unRandomSeed);
      }
      else {
         /* Prepare the default value based on the current clock time */
         struct timeval sTimeValue;
         ::gettimeofday(&sTimeValue, NULL);
         UInt32 unSeed = static_cast<UInt32>(sTimeValue.tv_usec);
         CRandom::SetSeedOf("argos", unSeed);
         m_unRandomSeed = unSeed;
         LOG << "[INFO] Using random seed = " << m_unRandomSeed << std::endl;
      }
      CRandom::GetCategory("argos").ResetRNGs();
      /* Reset the space */
      m_pcSpace->Reset();
      /* Reset the media */
      for(CMedium::TMap::iterator it = m_mapMedia.begin();
          it != m_mapMedia.end(); ++it) {
         it->second->Reset();
      }
      /* Reset the physics engines */
      for(CPhysicsEngine::TMap::iterator it = m_mapPhysicsEngines.begin();
          it != m_mapPhysicsEngines.end(); ++it) {
         it->second->Reset();
      }
      /* Reset the loop functions */
      m_pcLoopFunctions->Reset();
      LOG.Flush();
      LOGERR.Flush();
   }

**Comment by daneshtarapore** [comment]
Hi David,

I think the problem is much more fundamental than the above. It is the
design choice of using forks in a multi-threaded process
(eval::Parallel -- tbb is mutithreaded). This has created a dangerous
situation for us. See
https://www.linuxprogrammingblog.com/threads-and-fork-think-twice-before-using-them
for starters.

Please see the following in the fork man page:
http://man7.org/linux/man-pages/man2/fork.2.html

       *  After a fork() in a multithreaded program, the child can safely
          call only async-signal-safe functions (see signal-safety(7)) until
          such time as it calls execve(2).

We are not calling execve(). So we have to be careful to make sure
that the child process calls only async-signal-safe functions between
fork and exit. The list of async-signal-safe functions is here
http://man7.org/linux/man-pages/man7/signal-safety.7.html

There is also the question of whether the child should exit with
exit(x) or _exit(x); see
https://stackoverflow.com/questions/4856255/the-difference-between-fork-vfork-exec-and-clone
"This means that the child process of a vfork() must be careful to
avoid unexpectedly modifying variables of the parent process. In
particular, the child process must not return from the function
containing the vfork() call, and it must not call exit() (if it needs
to exit, it should use _exit(); actually, this is also true for the
child of a normal fork()). "

Some more links that may be useful:
https://stackoverflow.com/questions/29919332/linux-forked-process-hangs-immediately
https://www.usna.edu/Users/cs/aviv/classes/ic221/s17/units/05/unit.html


So this is what we need to do:
1. Make sure we call only async-signal-safe functions functions in the child.
2. Look into exiting the child with _exit instead of exit -- but
understand why so first.
3. Create a fail-safe in the parent that wakesup if a child timesout;
it kills the child and restarts another child process. Am not sure
what's the best way to do it. I think signal handlers -- wake-up
signal -- may be useful place to start looking for solutions here.
What we don't want is wasted computation with the parent checking if
the child has not yet terminated
4. A more permanent solution would be to avoid forking from a
multithreaded process. Something like this.
---------------------------------------
Main process -- (M) -- argos::CSimulator has been instantinated but no
threads have yet been created
The job of the main process is to fork children to test controllers.
It will be requested to do so by its child (C) which will be running
sferes.

M -- forks children when requested by C.
|
C requests evaluation & waits for fitness and descriptors
|
C running eval::Parallel (multithreaded)
---------------------------------------

Please look through all this material and the links carefully. Does
this make sense? Let me know what you think.

Best,
Danesh.

**Comment by bossdm** [comment]
In the first link, the summary concludes that it is nearly impossible to fork in a multi-threaded program in a right way. Therefore I think we should avoid it.

I think it makes sense to somehow separate getting the fitness and descriptors from the simulator from the eval function. This would allow to create processes in parallel from the start and never touch them like in the mpga example (we can also do the intial sleep operation) and then also we do not need to fork from a multi-threaded process. 

This would require two-fold communication:
-eval sends a genotype to one of the available processes
-the process returns the fitness and descriptor

I am not sure how this communication would use. I have read about _pipe_ allowing inter-process communication but then it is not clear how that works to connect to a specific thread.
If somehow the multi-threaded eval is difficult to combine with the above idea, we could also use single-threaded eval because the time consumed by the simulator far outweighs the time by sferes.

**Comment by daneshtarapore** [comment]
On Sun, Jul 14, 2019 at 4:24 PM bossdm <notifications@github.com> wrote:

> In the first link, the summary concludes that it is nearly impossible to
> fork in a multi-threaded program in a right way. Therefore I think we
> should avoid it.
>
Do you read the other links and the rest of the email. I think there is
something we could do. You can look at your code and see if there are any
functions being called by the child that are not async-signal-safe. That
would be a temp fix for us.


> I think it makes sense to somehow separate getting the fitness and
> descriptors from the simulator from the eval function. This would allow to
> create processes in parallel from the start and never touch them like in
> the mpga example (we can also do the intial sleep operation) and then also
> we do not need to fork from a multi-threaded process.
>
This would require two-fold communication:
> -eval sends a genotype to one of the available processes
> -the process returns the fitness and descriptor
>
> I am not sure how this communication would use. I have read about *pipe*
> allowing inter-process communication but then it is not clear how that
> works to connect to a specific thread
>
This is similar to my last idea. But remember, we don't fork a multi-thread
process! We need an intermediary process. It will act as the interface.
Each of the threads will have its own block of shared memory to communicate
with this intermediary process. On getting a wakeup signal, they check
their individual shared memory block to see if any fitness value is written
on it. We could also use network sockets, wherein each thread has its own
socket for communication. Am not sure about how to share the neural network
to evaluate to shared memory.  Look at boost serialization which is also
what is used by sferes to write a generation to a file.  Boost
serialization makes it possible to convert objects in a C++ program to a
sequence of bytes that can be saved and loaded to restore the objects.


Another idea to prevent forking a multithreaded process is to clone the
argos simulator. As it stands, it is a singleton; but if there is a way to
clone it, we would not have to fork a multithreaded process. Can you post
on the argos forum and ask about it.Give some background about the problem
we are facing. Carlo may have some ideas.

> If somehow the multi-threaded eval is difficult to combine with the above
idea, we could also use single-threaded eval because the time consumed by
the simulator far outweighs the time by sferes.
With single-threaded eval, what would be the point. We won't be able to
parallelize. As sferes eval would be kept waiting for the simulator to
complete.

Best,
Danesh.


Best,
Danesh.

**Comment by bossdm** [comment]
Hi,

>  You can look at your code and see if there are any
functions being called by the child that are not async-signal-safe. 

I think this would mean I have to rewrite all the code since all the code is happening inside the child. therefore the temporary solution seems more difficult than the permanent solution.

> Another idea to prevent forking a multithreaded process is to clone the
argos simulator. 

Carlo replied that it is impossible to do. 


`Am not sure about how to share the neural network
to evaluate to shared memory.`

I think we could write to and read from a .dot file.

**Comment by daneshtarapore** [comment]
On Sun, Jul 14, 2019 at 8:46 PM bossdm <notifications@github.com> wrote:

> Hi,
>
> You can look at your code and see if there are any
> functions being called by the child that are not async-signal-safe.
>
> I think this would mean I have to rewrite all the code since all the code
> is happening inside the child. therefore the temporary solution seems more
> difficult than the permanent solution.
>
Okay, but what part of your code is not using async-signal-safe functions.
We can just focus on them.


> Another idea to prevent forking a multithreaded process is to clone the
> argos simulator.
>
> Carlo replied that it is impossible to do.
>
Okay, thanks for asking. Did he have any suggestions?


> Am not sure about how to share the neural network to evaluate to shared
> memory.
>
> I think we could write to and read from a .dot file.
>
I/O disk operations are very expensive. Not sure if it would help. As I
suggested earlier, using boost serialize would be better.

Best,
Danesh.

**Comment by bossdm** [comment]
> Okay, but what part of your code is not using async-signal-safe functions.
> We can just focus on them.

To know that, we would need a list of the _un_safe operations. Otherwise I am thinking all of the code is unsafe.

Carlo said it is best to follow the mpga example, because creating and destroying instances is quite expensive. Before, I had asked him about the LOG issue, he suggests to use one log-file per process, but that may be bad in our case; another approach he suggested is to redirect to '/dev/null' instead.

**Comment by daneshtarapore** [comment]
On Sun, Jul 14, 2019 at 9:22 PM bossdm <notifications@github.com> wrote:

> Okay, but what part of your code is not using async-signal-safe functions.
> We can just focus on them.
>
> To know that, we would need a list of the _un_safe operations. Otherwise I
> am thinking all of the code is unsafe.
>
The link I sent is a list of safe operations. Anything out of that will be
unsafe.

>
> Carlo said it is best to follow the mpga example, because creating and
> destroying instances is quite expensive. Before, I had asked him about the
> LOG issue, he suggests to use one log-file per process, but that may be bad
> in our case; another approach he suggested is to redirect to '/dev/null'
> instead.
>

Okay. We can talk about this tomorrow.

Best,
Danesh.

**Comment by bossdm** [comment]
I was thinking maybe we could make our own version of parallel_eval for sferes evaluation. then we can use the mpga code as a template, without needing threads.

**Comment by daneshtarapore** [comment]
Am not sure I get exactly how you want to accomplish this. Let's discuss
this today.

Best,
Danesh.
