### ISSUE TITLE
Errors in compiling code on IRIDIS5

### ISSUE THREAD

**Issue by daneshtarapore** [resilient-swarms/argos-sferes#3]
Hi David,

I have updated the cmake script and pushed it to the repo.

But am now getting compilation errors on parts of the code you modified. Can you please take a look.

dst1m17@cyan53 /home/dst1m17/argos-sferes/build>make
[  4%] Automatic MOC for target obsavoid_nn_controller
[  4%] Built target obsavoid_nn_controller_autogen
[ 16%] Built target obsavoid_nn_controller
[ 20%] Automatic MOC for target obsavoid_evol_loopfunctions
[ 20%] Built target obsavoid_evol_loopfunctions_autogen
[ 25%] Building CXX object CMakeFiles/obsavoid_evol_loopfunctions.dir/src/obsavoid/evol_loop_functions.cpp.o
In file included from /home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.cpp:4:0:
/home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.h: In member function 'void sferes::FitObstacleMapElites<Params, Exact>::print_progress(Indiv&, CObsAvoidEvolLoopFunctions&, argos::Real)':
/home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.h:308:86: error: invalid use of incomplete type 'class FitFun'
                 printf("\n\n fitness in trial %lu is %f", trial,cLoopFunctions.fitfun->fitness_per_trial[trial]);
                                                                                      ^
In file included from /home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.cpp:4:0:
/home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.h:174:7: error: forward declaration of 'class FitFun'
 class FitFun;
       ^
In file included from /home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.cpp:4:0:
/home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.h: In member function 'void sferes::FitObstacleMapElites<Params, Exact>::eval(Indiv&)':
/home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.h:344:34: error: invalid use of incomplete type 'class Descriptor'
         cLoopFunctions.descriptor->before_trials(cLoopFunctions);
                                  ^
In file included from /home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.cpp:4:0:
/home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.h:172:7: error: forward declaration of 'class Descriptor'
 class Descriptor;
       ^
In file included from /home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.cpp:4:0:
/home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.h:359:38: error: invalid use of incomplete type 'class Descriptor'
             cLoopFunctions.descriptor->start_trial();
                                      ^
In file included from /home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.cpp:4:0:
/home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.h:172:7: error: forward declaration of 'class Descriptor'
 class Descriptor;
       ^
In file included from /home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.cpp:4:0:
/home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.h:383:34: error: invalid use of incomplete type 'class FitFun'
             cLoopFunctions.fitfun->apply(cLoopFunctions,time);
                                  ^
In file included from /home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.cpp:4:0:
/home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.h:174:7: error: forward declaration of 'class FitFun'
 class FitFun;
       ^
In file included from /home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.cpp:4:0:
/home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.h:389:38: error: invalid use of incomplete type 'class Descriptor'
             cLoopFunctions.descriptor->end_trial(cLoopFunctions);
                                      ^
In file included from /home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.cpp:4:0:
/home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.h:172:7: error: forward declaration of 'class Descriptor'
 class Descriptor;
       ^
In file included from /home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.cpp:4:0:
/home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.h:396:45: error: invalid use of incomplete type 'class FitFun'
         float fFitness=cLoopFunctions.fitfun->after_trials();
                                             ^
In file included from /home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.cpp:4:0:
/home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.h:174:7: error: forward declaration of 'class FitFun'
 class FitFun;
       ^
In file included from /home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.cpp:4:0:
/home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.h:401:76: error: invalid use of incomplete type 'class Descriptor'
         std::vector<float> behavioural_descriptor=cLoopFunctions.descriptor->after_trials(cLoopFunctions);
                                                                            ^
In file included from /home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.cpp:4:0:
/home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.h:172:7: error: forward declaration of 'class Descriptor'
 class Descriptor;
       ^
In file included from /home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.cpp:5:0:
/home/dst1m17/argos-sferes/src/obsavoid/statistics.h: At global scope:
/home/dst1m17/argos-sferes/src/obsavoid/statistics.h:60:50: warning: converting to non-pointer type 'size_t {aka long unsigned int}' from NULL [-Wconversion-null]
     static float log(float number, size_t base = NULL);
                                                  ^
/home/dst1m17/argos-sferes/src/obsavoid/statistics.h:92:92: warning: converting to non-pointer type 'size_t {aka long unsigned int}' from NULL [-Wconversion-null]
     static std::pair<float, float> entropy(std::vector<float> p, float time, size_t base = NULL);
                                                                                            ^
/home/dst1m17/argos-sferes/src/obsavoid/statistics.h:93:108: warning: converting to non-pointer type 'size_t {aka long unsigned int}' from NULL [-Wconversion-null]
     static float joint_entropy(std::vector<float> joint_p, float S_x, float S_y, float time, size_t base = NULL);
                                                                                                            ^
In file included from /home/dst1m17/argos-sferes/src/obsavoid/evol_loop_functions.cpp:5:0:
/home/dst1m17/argos-sferes/src/obsavoid/statistics.h:94:139: warning: converting to non-pointer type 'size_t {aka long unsigned int}' from NULL [-Wconversion-null]
     static float mutual_information(std::vector<float> joint_p, std::vector<float> p_x, std::vector<float> p_y, float time, size_t base = NULL);
                                                                                                                                           ^
make[2]: *** [CMakeFiles/obsavoid_evol_loopfunctions.dir/src/obsavoid/evol_loop_functions.cpp.o] Error 1
make[1]: *** [CMakeFiles/obsavoid_evol_loopfunctions.dir/all] Error 2
make: *** [all] Error 2

**Comment by bossdm** [comment]
It looks like the compiler is not allowing forward declarations. On my system these are warnings, maybe it is due to the compiler.

**Comment by bossdm** [comment]
This issue is now solved; I removed the errors and warnings. The make procedure works for me, save for some linker errors, related to tbb it seems, both on iridis5 and on my system.


On iridis5:
undefined reference to symbol 'pthread_join@@GLIBC_2.2.5'
/usr/lib64/libpthread.so.0: error adding symbols: DSO missing from command line

On my system:
tbb::task_scheduler_init::task_scheduler_init(int, unsigned long)':
main.cpp:(.text._ZN3tbb19task_scheduler_initC2Eim[_ZN3tbb19task_scheduler_initC5Eim]+0x40): undefined reference to `tbb::task_scheduler_init::initialize(int, unsigned long)'
CMakeFiles/obsavoid_evol3D.dir/src/obsavoid/main.cpp.o: In function `tbb::task_scheduler_init::~task_scheduler_init()':
main.cpp:(.text._ZN3tbb19task_scheduler_initD2Ev[_ZN3tbb19task_scheduler_initD5Ev]+0x20): undefined reference to `tbb::task_scheduler_init::terminate()
