### ISSUE TITLE
Linker errors

### ISSUE THREAD

**Issue by bossdm** [resilient-swarms/argos-sferes#6]
I am still experiencing some linker errors.

Locally I was able to run the new version, with the exception that I needed to add lua to the includes in the CMakeLists.txt.

On Iridis5, I got the following linker errors:

/home/dmb1m19/thymio/lib/argos3/libargos3plugin_simulator_thymio.so: undefined reference to `argos::CEntity::GetContext[abi:cxx11]() const'
/home/dmb1m19/thymio/lib/argos3/libargos3plugin_simulator_thymio.so: undefined reference to `argos::CLuaUtility::AddToTable(lua_State*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, argos::CVector2 const&)'
../lib/libobsavoid_evol_loopfunctions.so: undefined reference to `ticpp::Element::GetAttributeImp(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*) const'
/home/dmb1m19/thymio/lib/argos3/libargos3plugin_simulator_thymio.so: undefined reference to `argos::CLuaUtility::AddToTable(lua_State*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, argos::CRadians const&)'
../lib/libobsavoid_evol_loopfunctions.so: undefined reference to `ticpp::Exception::Exception(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/dmb1m19/thymio/lib/argos3/libargos3plugin_simulator_thymio.so: undefined reference to `argos::CControllableEntity::SetController(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/dmb1m19/thymio/lib/argos3/libargos3plugin_simulator_thymio.so: undefined reference to `argos::CDynamics2DEngine::AddPhysicsModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, argos::CDynamics2DModel&)'
/home/dmb1m19/thymio/lib/argos3/libargos3plugin_simulator_thymio.so: undefined reference to `argos::CComposableEntity::GetComponent(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/dmb1m19/thymio/lib/argos3/libargos3plugin_simulator_thymio.so: undefined reference to `argos::CWheeledEntity::CWheeledEntity(argos::CComposableEntity*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)'
../lib/libobsavoid_evol_loopfunctions.so: undefined reference to `argos::CSpace::GetEntitiesByType(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/dmb1m19/thymio/lib/argos3/libargos3plugin_simulator_thymio.so: undefined reference to `argos::CDynamics2DEngine::RemovePhysicsModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/dmb1m19/thymio/lib/argos3/libargos3plugin_simulator_thymio.so: undefined reference to `argos::CLEDEquippedEntity::CLEDEquippedEntity(argos::CComposableEntity*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/dmb1m19/thymio/lib/argos3/libargos3plugin_simulator_thymio.so: undefined reference to `argos::CBatteryEquippedEntity::CBatteryEquippedEntity(argos::CComposableEntity*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, double, double)'
/home/dmb1m19/thymio/lib/argos3/libargos3plugin_simulator_thymio.so: undefined reference to `argos::CGroundSensorEquippedEntity::CGroundSensorEquippedEntity(argos::CComposableEntity*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/dmb1m19/thymio/lib/argos3/libargos3plugin_simulator_thymio.so: undefined reference to `argos::CEmbodiedEntity::RemovePhysicsModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/dmb1m19/thymio/lib/argos3/libargos3plugin_simulator_thymio.so: undefined reference to `argos::CComposableEntity::RemoveComponent(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/dmb1m19/thymio/lib/argos3/libargos3plugin_simulator_thymio.so: undefined reference to `argos::CProximitySensorEquippedEntity::CProximitySensorEquippedEntity(argos::CComposableEntity*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../lib/libobsavoid_evol_loopfunctions.so: undefined reference to `argos::CLoopFunctions::RemoveEntity(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/dmb1m19/thymio/lib/argos3/libargos3plugin_simulator_thymio.so: undefined reference to `ticpp::Node::FirstChild(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) const'
/home/dmb1m19/thymio/lib/argos3/libargos3plugin_simulator_thymio.so: undefined reference to `argos::CBatteryEquippedEntity::CBatteryEquippedEntity(argos::CComposableEntity*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, argos::CBatteryDischargeModel*, double, double)'
/home/dmb1m19/thymio/lib/argos3/libargos3plugin_simulator_thymio.so: undefined reference to `argos::CLuaUtility::AddToTable(lua_State*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, double)'
/home/dmb1m19/thymio/lib/argos3/libargos3plugin_simulator_thymio.so: undefined reference to `argos::CLuaUtility::OpenRobotStateTable(lua_State*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/dmb1m19/thymio/lib/argos3/libargos3plugin_simulator_thymio.so: undefined reference to `argos::CControllableEntity::CControllableEntity(argos::CComposableEntity*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/home/dmb1m19/thymio/lib/argos3/libargos3plugin_simulator_thymio.so: undefined reference to `ticpp::Node::NextSibling(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) const'
/home/dmb1m19/thymio/lib/argos3/libargos3plugin_simulator_thymio.so: undefined reference to `argos::CEmbodiedEntity::CEmbodiedEntity(argos::CComposableEntity*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, argos::CVector3 const&, argos::CQuaternion const&, bool)'
/home/dmb1m19/thymio/lib/argos3/libargos3plugin_simulator_thymio.so: undefined reference to `argos::CComposableEntity::CComposableEntity(argos::CComposableEntity*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../lib/libobsavoid_evol_loopfunctions.so: undefined reference to `argos::CRandom::CreateRNG(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'

**Comment by daneshtarapore** [comment]
Please use the following for now in your .bash_profile:

LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/local/software/lua/5.3.4/lib
export LD_LIBRARY_PATH

CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/local/software/lua/5.3.4/include
export CPLUS_INCLUDE_PATH

Will try to get a better fix to this issue soon.

--D

**Comment by bossdm** [comment]
I already had these settings, so this does not appear to be the issue.

**Comment by daneshtarapore** [comment]
Can take a look at it tomorrow.

--D

**Comment by daneshtarapore** [comment]
Can you give me the output of 'module list'

**Comment by daneshtarapore** [comment]
Also can you make sure you have pushed your CMake file so I can take a look and try to replicate your errors.
