### ISSUE TITLE
issue with cmakelists.txt

### ISSUE THREAD

**Issue by bossdm** [resilient-swarms/argos-sferes#7]
Hi Danesh,

With the new CMakeLists.txt,I get the following:

-- Boost version: 1.66.0
-- Found the following Boost libraries:
--   serialization
--   graph
--   program_options
--   filesystem
--   system
Boost libs found in: /local/software/boost/1.66.0/lib
Boost headers found in: /local/software/boost/1.66.0/include
-- Could NOT find TBB (missing: TBB_INCLUDE_DIRS) 
Unable to find TBB. Will not be able to run sferes eval::Parallel
-- Found OpenGL: /usr/lib64/libGL.so   
-- Found GLUT: /usr/lib64/libglut.so  
-- Found GSL: /local/software/gsl/2.4/include (found version "2.4") 
-- Could NOT find Lua52 (missing: LUA_LIBRARIES LUA_INCLUDE_DIR) 
CMake Error at CMakeLists.txt:93 (MESSAGE):
  Please point the environment variable LUA_DIR to your Lua installation --
  include and lib.

-- Configuring incomplete, errors occurred!
See also "/home/dmb1m19/argos-sferes/build/CMakeFiles/CMakeOutput.log".

**Comment by daneshtarapore** [comment]
Can you give me the output of the following:
> export

**Comment by bossdm** [comment]
declare -x ACLOCAL_PATH="/local/software/gsl/2.4/share/aclocal:/local/software/cmake/3.10.2/share/aclocal"
declare -x ARGOS_INCLUDE_DIRS="/local/software/argos3/current/include:/home/dmb1m19/thymio/src"
declare -x ARGOS_PLUGIN_PATH="/home/david/thymio/build/"
declare -x BASH_ENV="/usr/share/lmod/lmod/init/bash"
declare -x BOOST_INCLUDE_DIR="/local/software/boost/1.66.0/include"
declare -x BOOST_ROOT="/local/software/boost/1.66.0/"
declare -x CPATH="/local/software/intel-tbb/2018.1/include"
declare -x CPLUS_INCLUDE_PATH="::/local/software/argos3/current/include:/local/software/lua/5.3.4/include:/local/software/eigen/3.3.7/include:/local/software/eigen/3.3.7/include:/local/software/boost/1.66.0/include:/local/software/argos3/current/include:/home/dmb1m19/thymio/src"
declare -x EIGEN3_INCLUDE_DIR="/local/software/eigen/3.3.7/include"
declare -x HISTCONTROL="ignoredups"
declare -x HISTSIZE="1000"
declare -x HOME="/home/dmb1m19"
declare -x HOSTNAME="cyan53.cluster.local"
declare -x INCLUDE="/local/software/boost/1.66.0/include"
declare -x KDEDIRS="/usr"
declare -x KRB5CCNAME="KEYRING:persistent:95115"
declare -x LANG="en_GB.UTF-8"
declare -x LC_ALL="POSIX"
declare -x LC_CTYPE="POSIX"
declare -x LD_LIBRARY_PATH="/local/software/intel-tbb/2018.1/lib:/local/software/argos3/current/lib/argos3:/local/software/qt/5.10.1/lib:/local/software/gsl/2.4/lib:/local/software/boost/1.66.0/lib:/local/software/argos3/current/lib::/local/software/lua/5.3.4/lib:/usr/lib"
declare -x LESSOPEN="||/usr/bin/lesspipe.sh %s"
declare -x LIBRARY_PATH="/local/software/intel-tbb/2018.1/lib:/local/software/argos3/current/lib/argos3:/local/software/qt/5.10.1/lib:/local/software/gsl/2.4/lib:/local/software/boost/1.66.0/lib"
declare -x LMOD_CMD="/usr/share/lmod/lmod/libexec/lmod"
declare -x LMOD_COLORIZE="yes"
declare -x LMOD_DEFAULT_MODULEPATH="/local/modules/custom:/local/modules/eb/all:/local/modules/apps:/local/modules/compilers:/local/modules/libs:/local/modules/misc:/local/modules/mpi:/etc/modulefiles:/usr/share/modulefiles:/usr/share/modulefiles/Linux:/usr/share/modulefiles/Core:/usr/share/lmod/lmod/modulefiles/Core"
declare -x LMOD_DIR="/usr/share/lmod/lmod/libexec"
declare -x LMOD_FULL_SETTARG_SUPPORT="no"
declare -x LMOD_PKG="/usr/share/lmod/lmod"
declare -x LMOD_PREPEND_BLOCK="normal"
declare -x LMOD_SETTARG_CMD=":"
declare -x LMOD_VERSION="6.5.1"
declare -x LMOD_arch="x86_64"
declare -x LMOD_sys="Linux"
declare -x LOADEDMODULES="cmake/3.10.2:boost/1.66.0:gsl/2.4:qt/5.10.1:argos/3.0.0:intel-tbb/2018.1"
declare -x LOGNAME="dmb1m19"
declare -x LS_COLORS="rs=0:di=38;5;27:ln=38;5;51:mh=44;38;5;15:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=05;48;5;232;38;5;15:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;34:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.Z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.axv=38;5;13:*.anx=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.axa=38;5;45:*.oga=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:"
declare -x LUA_INCLUDE_DIR="/local/software/lua/5.3.4/include"
declare -x LUA_LIB_DIRS="/local/software/lua/5.3.4/lib"
declare -x MAIL="/var/spool/mail/dmb1m19"
declare -x MANPATH="/local/software/argos3/current/share/man:/local/software/gsl/2.4/share/man:/usr/share/lmod/lmod/share/man::"
declare -x MODULEPATH="/local/modules/custom:/local/modules/eb/all:/local/modules/apps:/local/modules/compilers:/local/modules/libs:/local/modules/misc:/local/modules/mpi:/etc/modulefiles:/usr/share/modulefiles:/usr/share/modulefiles/Linux:/usr/share/modulefiles/Core:/usr/share/lmod/lmod/modulefiles/Core"
declare -x MODULEPATH_ROOT="/usr/share/modulefiles"
declare -x MODULESHOME="/usr/share/lmod/lmod"
declare -x OLDPWD="/home/dmb1m19/argos-sferes/build"
declare -x PATH="/local/software/argos3/current/bin:/local/software/qt/5.10.1/bin:/local/software/gsl/2.4/bin:/local/software/cmake/3.10.2/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/lpp/mmfs/bin:/home/dmb1m19/bin:/local/bin:/local/software/slurm/bin:."
declare -x PKG_CONFIG_PATH="/local/software/gsl/2.4/lib/pkgconfig:/local/software/argos3/current/lib/pkgconfig"
declare -x PWD="/home/dmb1m19/argos-sferes"
declare -x QTDIR="/usr/lib64/qt-3.3"
declare -x QTINC="/usr/lib64/qt-3.3/include"
declare -x QTLIB="/usr/lib64/qt-3.3/lib"
declare -x QT_GRAPHICSSYSTEM_CHECKED="1"
declare -x QT_PLUGIN_PATH="/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins"
declare -x SHELL="/bin/bash"
declare -x SHLVL="1"
declare -x SSH_CLIENT="10.9.184.77 39396 22"
declare -x SSH_CONNECTION="10.9.184.77 39396 152.78.188.162 22"
declare -x SSH_TTY="/dev/pts/25"
declare -x TERM="xterm-256color"
declare -x THYMIO="/home/dmb1m19/thymio"
declare -x USER="dmb1m19"
declare -x _LMFILES_="/local/modules/misc/cmake/3.10.2.lua:/local/modules/libs/boost/1.66.0.lua:/local/modules/libs/gsl/2.4.lua:/local/modules/libs/qt/5.10.1.lua:/local/modules/apps/argos/3.0.0.lua:/local/modules/libs/intel-tbb/2018.1.lua"
declare -x _ModuleTable001_="X01vZHVsZVRhYmxlXz17WyJhY3RpdmVTaXplIl09NixiYXNlTXBhdGhBPXsiL2xvY2FsL21vZHVsZXMvY3VzdG9tIiwiL2xvY2FsL21vZHVsZXMvZWIvYWxsIiwiL2xvY2FsL21vZHVsZXMvYXBwcyIsIi9sb2NhbC9tb2R1bGVzL2NvbXBpbGVycyIsIi9sb2NhbC9tb2R1bGVzL2xpYnMiLCIvbG9jYWwvbW9kdWxlcy9taXNjIiwiL2xvY2FsL21vZHVsZXMvbXBpIiwiL2V0Yy9tb2R1bGVmaWxlcyIsIi91c3Ivc2hhcmUvbW9kdWxlZmlsZXMiLCIvdXNyL3NoYXJlL21vZHVsZWZpbGVzL0xpbnV4IiwiL3Vzci9zaGFyZS9tb2R1bGVmaWxlcy9Db3JlIiwiL3Vzci9zaGFyZS9sbW9kL2xtb2QvbW9kdWxlZmlsZXMvQ29yZSIsfSxbImNfcmVidWlsZFRpbWUiXT1mYWxzZSxbImNfc2hv"
declare -x _ModuleTable002_="cnRUaW1lIl09ZmFsc2UsZmFtaWx5PXt9LGluYWN0aXZlPXt9LG1UPXthcmdvcz17WyJGTiJdPSIvbG9jYWwvbW9kdWxlcy9hcHBzL2FyZ29zLzMuMC4wLmx1YSIsWyJkZWZhdWx0Il09MCxbImZ1bGxOYW1lIl09ImFyZ29zLzMuMC4wIixbImxvYWRPcmRlciJdPTUscHJvcFQ9e30sWyJzaG9ydCJdPSJhcmdvcyIsWyJzdGF0dXMiXT0iYWN0aXZlIix9LGJvb3N0PXtbIkZOIl09Ii9sb2NhbC9tb2R1bGVzL2xpYnMvYm9vc3QvMS42Ni4wLmx1YSIsWyJkZWZhdWx0Il09MCxbImZ1bGxOYW1lIl09ImJvb3N0LzEuNjYuMCIsWyJsb2FkT3JkZXIiXT0yLHByb3BUPXt9LFsic2hvcnQiXT0iYm9vc3QiLFsic3RhdHVzIl09ImFjdGl2ZSIsfSxjbWFrZT17WyJGTiJdPSIvbG9jYWwvbW9k"
declare -x _ModuleTable003_="dWxlcy9taXNjL2NtYWtlLzMuMTAuMi5sdWEiLFsiZGVmYXVsdCJdPTAsWyJmdWxsTmFtZSJdPSJjbWFrZS8zLjEwLjIiLFsibG9hZE9yZGVyIl09MSxwcm9wVD17fSxbInNob3J0Il09ImNtYWtlIixbInN0YXR1cyJdPSJhY3RpdmUiLH0sZ3NsPXtbIkZOIl09Ii9sb2NhbC9tb2R1bGVzL2xpYnMvZ3NsLzIuNC5sdWEiLFsiZGVmYXVsdCJdPTAsWyJmdWxsTmFtZSJdPSJnc2wvMi40IixbImxvYWRPcmRlciJdPTMscHJvcFQ9e30sWyJzaG9ydCJdPSJnc2wiLFsic3RhdHVzIl09ImFjdGl2ZSIsfSxbImludGVsLXRiYiJdPXtbIkZOIl09Ii9sb2NhbC9tb2R1bGVzL2xpYnMvaW50ZWwtdGJiLzIwMTguMS5sdWEiLFsiZGVmYXVsdCJdPTAsWyJmdWxsTmFtZSJdPSJpbnRlbC10YmIv"
declare -x _ModuleTable004_="MjAxOC4xIixbImxvYWRPcmRlciJdPTYscHJvcFQ9e30sWyJzaG9ydCJdPSJpbnRlbC10YmIiLFsic3RhdHVzIl09ImFjdGl2ZSIsfSxxdD17WyJGTiJdPSIvbG9jYWwvbW9kdWxlcy9saWJzL3F0LzUuMTAuMS5sdWEiLFsiZGVmYXVsdCJdPTAsWyJmdWxsTmFtZSJdPSJxdC81LjEwLjEiLFsibG9hZE9yZGVyIl09NCxwcm9wVD17fSxbInNob3J0Il09InF0IixbInN0YXR1cyJdPSJhY3RpdmUiLH0sfSxtcGF0aEE9eyIvbG9jYWwvbW9kdWxlcy9jdXN0b20iLCIvbG9jYWwvbW9kdWxlcy9lYi9hbGwiLCIvbG9jYWwvbW9kdWxlcy9hcHBzIiwiL2xvY2FsL21vZHVsZXMvY29tcGlsZXJzIiwiL2xvY2FsL21vZHVsZXMvbGlicyIsIi9sb2NhbC9tb2R1bGVzL21pc2MiLCIvbG9jYWwv"
declare -x _ModuleTable005_="bW9kdWxlcy9tcGkiLCIvZXRjL21vZHVsZWZpbGVzIiwiL3Vzci9zaGFyZS9tb2R1bGVmaWxlcyIsIi91c3Ivc2hhcmUvbW9kdWxlZmlsZXMvTGludXgiLCIvdXNyL3NoYXJlL21vZHVsZWZpbGVzL0NvcmUiLCIvdXNyL3NoYXJlL2xtb2QvbG1vZC9tb2R1bGVmaWxlcy9Db3JlIix9LFsic3lzdGVtQmFzZU1QQVRIIl09Ii9sb2NhbC9tb2R1bGVzL2N1c3RvbTovbG9jYWwvbW9kdWxlcy9lYi9hbGw6L2xvY2FsL21vZHVsZXMvYXBwczovbG9jYWwvbW9kdWxlcy9jb21waWxlcnM6L2xvY2FsL21vZHVsZXMvbGliczovbG9jYWwvbW9kdWxlcy9taXNjOi9sb2NhbC9tb2R1bGVzL21waTovZXRjL21vZHVsZWZpbGVzOi91c3Ivc2hhcmUvbW9kdWxlZmlsZXM6L3Vzci9zaGFyZS9tb2R1"
declare -x _ModuleTable006_="bGVmaWxlcy9MaW51eDovdXNyL3NoYXJlL21vZHVsZWZpbGVzL0NvcmU6L3Vzci9zaGFyZS9sbW9kL2xtb2QvbW9kdWxlZmlsZXMvQ29yZSIsWyJ2ZXJzaW9uIl09Mix9"
declare -x _ModuleTable_Sz_="6"

**Comment by daneshtarapore** [comment]
You need to give cmake hints on where to find lua, they are given in the
LUA_DIR environment varialble. For this please set LUA_DIR to
"/local/software/lua/5.3.4"

--D

**Comment by bossdm** [comment]
ok thanks I just did export LUA_DIR=/local/software/lua/5.3.4 and now there is no more problem. I will put it in the .bashrc. Should we put the environment variables that need to be set in the documentation?

**Comment by bossdm** [comment]
seems like it was already included in .bashrc that is weird

**Comment by daneshtarapore** [comment]
Please try and put the exports in .bash_profile instead.

You can also update the README with the environment variables needed.

Cheers,
Danesh.
